apiVersion: v1
kind: Service
metadata:
  name: devsecops-app
  namespace: devsecops
  labels:
    app: devsecops-app
    app.kubernetes.io/name: devsecops-app
    app.kubernetes.io/part-of: devsecops-mean
spec:
  selector:
    app: devsecops-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops-app
  namespace: devsecops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: devsecops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsecops-app
                port:
                  number: 80
