apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: devsecops

patches:
  - target:
      kind: Deployment
      name: devsecops-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: mongodb
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

commonLabels:
  environment: dev
